### ISSUE TITLE
Bug: Image thumbnails display

### ISSUE THREAD

**Issue by lbesson** [c2corg/c2c_ui#1303]
**Describe the bug**
Vertical images inserted into documents are often too big and blurry

**Screenshots**
Example 1 (https://www.camptocamp.org/routes/53823/fr/tete-des-fetoules-arete-w):
![image](https://user-images.githubusercontent.com/127776/88691035-a06c2780-d0fc-11ea-9a5c-f243a1a6fbb6.png)

Example 2 (https://www.camptocamp.org/articles/269090/fr/les-coinceurs-protections-actives-coinceurs-mecaniques):
![image](https://user-images.githubusercontent.com/127776/88691469-3011d600-d0fd-11ea-826c-3e61e906df97.png)

**Additional context**
Current css is:
```css
figure[c2c\:size='MI'] {
  width: 25vw;
  max-width: 400px;
  img {
    width: 25vw;
    max-width: 400px;
  }
}
```
I don't know the reasoning behind (maybe some kind of mix between not too blurry, but still be 'big enough' one the page), but IMHO, we should have the same max-width and max-height.
Current state is well for horizontal images, but bad for vertical ones
